name: Create and update github repo
on:
  workflow_dispatch:
  push:

jobs:
 gitreposettings:
    runs-on: ubuntu-latest        
    env:
      GH_TOKEN: ${{ secrets.REPO_SECRET }}    
      OWNER: ${{ github.repository_owner }}
      #REPO: ${{ github.event.repository.name }}      
      #ORG: ${{ github.event.repository.owner.name }}
      REPO: repo2
      ORG: prasanthksalla      
      
    steps:     
        
        - name: Github Action for curl
          uses: wei/curl@v1.1.1         
     

        
        - name: adding teams to organization project
          run: |
           gh api \
           --method PUT \
           -H "Accept: application/vnd.github+json" \
           /orgs/"$ORG"/teams/whr_data_leads/repos/"$OWNER"/"$REPO" \
           -f permission='maintain'             

           gh api \
           --method PUT \
           -H "Accept: application/vnd.github+json" \
           /orgs/"$ORG"/teams/whr_devopsautomation/repos/"$OWNER"/"$REPO" \
           -f permission='admin' 
           
           gh api \
           --method PUT \
           -H "Accept: application/vnd.github+json" \
           /orgs/"$ORG"/teams/whr_data_devs/repos/"$OWNER"/"$REPO" \
           -f permission='maintain' 
           
        - name: adding branch protection rules
          run: |
            curl \
            -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.REPO_SECRET }}" \
            https://api.github.com/repos/"$OWNER"/"$REPO"/branches/main/protection \
            -d '{"required_status_checks":{"strict":true,"contexts":['']},"enforce_admins":null,"required_pull_request_reviews":{"required_approving_review_count":1},"restrictions":null}'

            curl \
            -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.REPO_SECRET }}" \
            https://api.github.com/repos/"$OWNER"/"$REPO"/branches/dev/protection \
            -d '{"required_status_checks":{"strict":true,"contexts":["Reports"]},"enforce_admins":null,"required_pull_request_reviews":{"required_approving_review_count":1},"restrictions":null}'

            curl \
            -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.REPO_SECRET }}" \
            https://api.github.com/repos/"$OWNER"/"$REPO"/branches/release/protection \
            -d '{"required_status_checks":{"strict":true,"contexts":["Reports"]},"enforce_admins":null,"required_pull_request_reviews":{"required_approving_review_count":1},"restrictions":null}'


        - name: adding webhook
          run: |
            curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.REPO_SECRET }}" \
            https://api.github.com/repos/"$OWNER"/"$REPO"/hooks \
            -d '{"name":"web","active":true,"events":["push"],"config":{"url":"https://example.com/git-webhook","content_type":"form","insecure_ssl":"0"}}'
