name: Create and update github repo
on:
  workflow_dispatch:

jobs:
 gitreposettings:
    runs-on: ubuntu-latest        
    env:
      GH_TOKEN: ${{ secrets.REPO_SECRET }}      
      #OWNER: ${{ github.repository_owner }}
      
    steps:
    
        - name: Github Action for curl
          uses: wei/curl@v1.1.1

        - name: update github repo
          run: |
           gh api \
           --method PATCH \
           -H "Accept: application/vnd.github+json" \
           /repos/prasha94/test \
           -f name='test' \
           -f description='changes are made to this repo settings' \
           -f homepage='https://github.com/prasanthksalla/test' \
           -F private=true \
           #-F has_issues=true \
           #-F has_projects=true \
           #-F has_wiki=true 
           #-F allow_auto_merge=true
           #-F allow_rebase_merge=true

           
