name: Create and update github repo
on:
  workflow_dispatch:
  push:

jobs:
 gitreposettings:
    runs-on: ubuntu-latest        
    env:
      GH_TOKEN: ${{ secrets.REPO_SECRET }}    
      OWNER: ${{ github.repository_owner }}
      #REPO: ${{ github.event.repository.name }}      
      #ORG: ${{ github.event.repository.owner.name }}
      REPO: automated_repo
      ORG: prasanthksalla      
      
    steps:     
        
        - name: Github Action for curl
          uses: wei/curl@v1.1.1
          
        - name: create organization repo
          run: |
            gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            /orgs/"$ORG"/repos \
            -f name="$REPO" \
            -f description='This is automated repo' \
            -f homepage='https://github.com' \
            -F private=false \
            -F has_issues=true \
            -F has_projects=false \
            -F has_wiki=true 
            
        - name: Commit readme to GitHubRepo
          run: |
            echo "# created $repo and ready to use" >> README.md
            git init
            git config --global user.email "you@example.com"
            git config --global user.name "$OWNER"
            git branch -M main
            git config --global init.defaultBranch main
            git add README.md
            git commit -m "commit readme"            
            git remote add origin https://github.com/"$ORG"/"$REPO".git
            git push -u origin main
        
        - name: adding teams to organization project
          run: |
           gh api \
           --method PUT \
           -H "Accept: application/vnd.github+json" \
           /orgs/"$ORG"/teams/whr_data_leads/repos/"$OWNER"/"$REPO" \
           -f permission='maintain'             

           gh api \
           --method PUT \
           -H "Accept: application/vnd.github+json" \
           /orgs/"$ORG"/teams/whr_devopsautomation/repos/"$OWNER"/"$REPO" \
           -f permission='admin' 
           
           gh api \
           --method PUT \
           -H "Accept: application/vnd.github+json" \
           /orgs/"$ORG"/teams/whr_data_devs/repos/"$OWNER"/"$REPO" \
           -f permission='maintain' 
           
        - name: adding branch protection rules
          run: |
            curl \
            -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.REPO_SECRET }}" \
            https://api.github.com/repos/"$OWNER"/"$REPO"/branches/main/protection \
            -d '{"required_status_checks":{"strict":true,"contexts":['']},"enforce_admins":null,"required_pull_request_reviews":{"required_approving_review_count":1},"restrictions":null}'

            curl \
            -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.REPO_SECRET }}" \
            https://api.github.com/repos/"$OWNER"/"$REPO"/branches/dev/protection \
            -d '{"required_status_checks":{"strict":true,"contexts":["Reports"]},"enforce_admins":null,"required_pull_request_reviews":{"required_approving_review_count":1},"restrictions":null}'

            curl \
            -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.REPO_SECRET }}" \
            https://api.github.com/repos/"$OWNER"/"$REPO"/branches/release/protection \
            -d '{"required_status_checks":{"strict":true,"contexts":["Reports"]},"enforce_admins":null,"required_pull_request_reviews":{"required_approving_review_count":1},"restrictions":null}'


        - name: adding webhook
          run: |
            curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.REPO_SECRET }}" \
            https://api.github.com/repos/"$OWNER"/"$REPO"/hooks \
            -d '{"name":"web","active":true,"events":["push"],"config":{"url":"https://example.com/git-webhook","content_type":"form","insecure_ssl":"0"}}'
