name: Create and update github repo
on:
  workflow_dispatch:

jobs:
 gitreposettings:
    runs-on: ubuntu-latest        
    env:
      GITHUB_TOKEN: ${{ secrets.ORG_SECRET }}      
      #OWNER: ${{ github.repository_owner }}
      
    steps:
        - name: create a repo
          run: |
          
            curl -X POST \
            -H "Accept: application/vnd.github+json" 
            -H "Authorization: Bearer ${GITHUB_TOKEN}" \
            https://api.github.com/orgs/prasanthksalla/repos 
            -d '{"name":"automatedrepo","description":"This is my first repository","homepage":"https://github.com","private":true,"has_issues":true,"has_projects":true,"has_wiki":true,"allow_squash_merge":true,"allow_rebase_merge":true,}'
  

           
        - name: create branch protection
          run: |
          
           curl -X PUT \
           -H "Accept: application/vnd.github+json" \
           -H "Authorization: Bearer <YOUR-TOKEN>" \
            https://api.github.com/repos/OWNER/REPO/branches/BRANCH/protection \
            -d '{"required_status_checks":{"strict":true,"contexts":["continuous-integration/travis-ci"]},"enforce_admins":true,"required_pull_request_reviews":{"dismissal_restrictions":{"users":["octocat"],"teams":["justice-league"]},"dismiss_stale_reviews":true,"require_code_owner_reviews":true,"required_approving_review_count":2,"require_last_push_approval":true,"bypass_pull_request_allowances":{"users":["octocat"],"teams":["justice-league"]}},"restrictions":{"users":["octocat"],"teams":["justice-league"],"apps":["super-ci"]},"required_linear_history":true,"allow_force_pushes":true,"allow_deletions":true,"block_creations":true,"required_conversation_resolution":true,"lock_branch":true,"allow_fork_syncing":true}'
           
        - name: create webhook and configure
          run: |       

           curl -X POST \
           -H "Accept: application/vnd.github+json" \
           -H "Authorization: Bearer <YOUR-TOKEN>" \
           https://api.github.com/repos/OWNER/REPO/hooks \
           -d '{"name":"web","active":true,"events":["push","pull_request"],"config":{"url":"https://example.com/webhook","content_type":"json","insecure_ssl":"0","events":"push","active":"true"}}'
