name: Create and update github repo
on:
  workflow_dispatch:
  push:

jobs:
 gitreposettings:
    runs-on: ubuntu-latest        
    env:
      GH_TOKEN: ${{ secrets.REPO_SECRET }}      
      #OWNER: ${{ github.repository_owner }}
      
    steps:    
        - name: Github Action for curl
          uses: wei/curl@v1.1.1

        - name: update github repo
          run: |
           gh api \
           --method PATCH \
           -H "Accept: application/vnd.github+json" \
           /repos/prasha94/test \
           -f name='test' \
           -f description='changes are made to this repo settings' \
           -f homepage='https://github.com/prasanthksalla/test' \
           -F private=true \
           -F has_wiki=true 
        
        - name: adding teams to organization project
          run: |
           gh api \
           --method PUT \
           -H "Accept: application/vnd.github+json" \
           /orgs/prasanthksalla/teams/whr_data_leads/repos/prasanthksalla/test \
           -f permission='maintain'             

           gh api \
           --method PUT \
           -H "Accept: application/vnd.github+json" \
           /orgs/prasanthksalla/teams/whr_devopsautomation/repos/prasanthksalla/test \
           -f permission='admin' 
           
           #gh api \
           #--method PUT \
           #-H "Accept: application/vnd.github+json" \
           #/orgs/prasanthksalla/teams/whr_devs/repos/prasanthksalla/test \
           #-f permission='write' 
           
           gh api \
           --method PUT \
           -H "Accept: application/vnd.github+json" \
           /orgs/prasanthksalla/teams/whr_devs/projects/test \
           -f permission='write' 
           

           
 


           
