name: Action File Sync
on:
  push:
  workflow_dispatch:

jobs:
  Action_file_sync:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.REPO_SECRET }}    
      OWNER: ${{ github.repository_owner }}
      REPO: ${{ github.event.repository.name }}      
      ORG: ${{ github.event.repository.owner.name }}
      
    steps:
      - name: Fetching Local Repository
        uses: actions/checkout@master
      - name: Action File Sync
        uses: kbrashears5/github-action-file-sync@v2.0.0
        with:
          REPOSITORIES: |
            prasanthksalla/sample@main
            prasanthksalla/something@main
            prasanthksalla/prashaprivate@main              
            
            
          FILES: |
            .github/workflows/githubreposettings.yml=.github/workflows/githubreposettings.yml
          TOKEN: ${{ secrets.REPO_SECRET }}
